CREATE TABLE `person` (
	`id` BIGINT(20) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`first_name` VARCHAR(80) NOT NULL,
	`last_name` VARCHAR(80) NOT NULL,
	`address` VARCHAR(100) NOT NULL,
	`gender` VARCHAR(6) NOT NULL
);